services:
  codesa-postgres:
    image: 'postgres:16'
    container_name: codesa-postgres
    env_file:
      - bd.env
    ports:
      - '5432:5432'
    volumes:
      - codesa_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - codesa-network

  api-auth:
    build:
      context: ./api-auth
      dockerfile: Dockerfile
    container_name: api-auth
    ports:
      - '8081:8081'
    env_file:
      - dev.env
    depends_on:
      codesa-postgres:
        condition: service_healthy
    networks:
      - codesa-network

  api-proyectos:
    build:
      context: ./api-proyectos
      dockerfile: Dockerfile
    container_name: api-proyectos
    ports:
      - '8082:8082'
    env_file:
      - dev.env
    depends_on:
      codesa-postgres:
        condition: service_healthy
    networks:
      - codesa-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - '8080:8080'
    env_file:
      - dev.env
    depends_on:
      - api-auth
      - api-proyectos
    networks:
      - codesa-network

volumes:
  codesa_pgdata:

networks:
  codesa-network:
    driver: bridge
